CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL,
    enabled BOOLEAN DEFAULT TRUE NOT NULL
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL
);

CREATE TABLE todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    author VARCHAR(50),
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    due_date DATE,
    priority VARCHAR(10) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT,
    CONSTRAINT fk_todos_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_todos_category FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE todo_edit_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    admin_user_id BIGINT NOT NULL,
    target_user_id BIGINT NOT NULL,
    before_title VARCHAR(100),
    after_title VARCHAR(100),
    before_description VARCHAR(500),
    after_description VARCHAR(500),
    before_priority VARCHAR(10),
    after_priority VARCHAR(10),
    before_due_date DATE,
    after_due_date DATE,
    before_category_id BIGINT,
    after_category_id BIGINT,
    edited_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_edit_log_todo FOREIGN KEY (todo_id) REFERENCES todos(id),
    CONSTRAINT fk_edit_log_admin FOREIGN KEY (admin_user_id) REFERENCES users(id),
    CONSTRAINT fk_edit_log_target FOREIGN KEY (target_user_id) REFERENCES users(id)
);

CREATE TABLE todo_attachments (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    todo_id BIGINT NOT NULL,
    original_name VARCHAR(255) NOT NULL,
    stored_name VARCHAR(255) NOT NULL,
    content_type VARCHAR(100),
    size BIGINT NOT NULL,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT fk_attachments_todo FOREIGN KEY (todo_id) REFERENCES todos(id)
);
