CREATE TABLE users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username VARCHAR(50) NOT NULL UNIQUE,
    password VARCHAR(100) NOT NULL,
    role VARCHAR(20) NOT NULL
);

CREATE TABLE categories (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL UNIQUE,
    color VARCHAR(20) NOT NULL
);

CREATE TABLE todos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    description VARCHAR(500),
    author VARCHAR(50),
    user_id BIGINT NOT NULL,
    category_id BIGINT,
    due_date DATE,
    priority VARCHAR(10) NOT NULL,
    completed BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP,
    updated_at TIMESTAMP,
    version BIGINT,
    CONSTRAINT fk_todos_user FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_todos_category FOREIGN KEY (category_id) REFERENCES categories(id)
);
